galaxy_info:
  author: froyo75
  description: Install, setup and configure a new ax controller
  company: froyo75
  license: MIT

  min_ansible_version: 2.4

  galaxy_tags:
    - ax
    - recon

dependencies: []